

INSERT INTO PRECOS(ORIGEM,DESTINO,PRECO) VALUES(11,16,1.90);
INSERT INTO PRECOS(ORIGEM,DESTINO,PRECO) VALUES(16,11,2.90);
INSERT INTO PRECOS(ORIGEM,DESTINO,PRECO) VALUES(11,17,1.70);
INSERT INTO PRECOS(ORIGEM,DESTINO,PRECO) VALUES(17,11,2.70);
INSERT INTO PRECOS(ORIGEM,DESTINO,PRECO) VALUES(11,18,0.90);
INSERT INTO PRECOS(ORIGEM,DESTINO,PRECO) VALUES(18,11,1.90);

--INSERT INTO PRODUTO(DESTINO,MIN_EXCEDENTE,ORIGEM,PLANO,TEMPO,VALOR_PLANO,PRECOS_ID) VALUES(16,10,11,'true',30,20,1);


INSERT INTO PLANOS(PRECOS) VALUES(0);
INSERT INTO PLANOS(PRECOS) VALUES(30);
INSERT INTO PLANOS(PRECOS) VALUES(60);
INSERT INTO PLANOS(PRECOS) VALUES(120);